services:
  - type: web
    name: itt-platform
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --legacy-peer-deps
    startCommand: node server-min.js
    envVars:
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://it-t.vercel.app/
      - key: CLOUDINARY_CLOUD_NAME
        value: xsyu1vh0
      - key: CLOUDINARY_API_KEY
        value: "399389216355614"
      - key: CLOUDINARY_API_SECRET
        value: -HO1drNBZlJ8Vvx9lxr6LfSyK2w
      - key: SMTP_HOST
        value: smtp-relay.brevo.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        value: "Trading App EMS" <b0c4cb001@smtp-brevo.com>
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
